name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: echo tokens
      run: |
        echo URL: $ACTIONS_ID_TOKEN_REQUEST_URL
        echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | base64


    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.0
